更新restart命令

diff --git a/recipes/templates/unicorn_init.erb b/recipes/templates/unicorn_init.erb
--- a/recipes/templates/unicorn_init.erb
+++ b/recipes/templates/unicorn_init.erb
@@ -49,7 +49,12 @@ force-stop)
   sig TERM && exit 0
   echo >&2 "Not running"
   ;;
-restart|reload)
+restart)
+  sig USR2 && sleep 5 && oldsig QUIT && echo "Killing old master" `cat $OLD_PID` && exit 0
+  echo >&2 "Couldn't restart, starting '$CMD' instead"
+  run $CMD
+  ;;
+reload)
   sig HUP && echo reloaded OK && exit 0
   echo >&2 "Couldn't reload, starting '$CMD' instead"
   run "$CMD"
